import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../lib/generated/prisma/client';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const categories = [
  {
    id: "pin-loaded",
    name: "JF Pin Loaded Series",
    blurb: "Selectorized commercial strength equipment engineered for smooth motion and isolation.",
  },
  {
    id: "hammer",
    name: "JF Hammer Equipment's",
    blurb: "Plate-loaded Iso-Lateral strength machines designed for maximum leverage and natural motion.",
  },
  {
    id: "benches-utilities",
    name: "JF Benches & Utilities",
    blurb: "Heavy-duty commercial benches, racks, and utility equipment.",
  },
  {
    id: "gym-accessories",
    name: "JF GYM Accessories",
    blurb: "Commercial dumbbells, plates, bumper plates, and rubber flooring mats.",
  },
  {
    id: "professional-tools",
    name: "JF Manufacturing & Powder Coating",
    blurb: "In-house manufacturing machinery and professional powder coating facility.",
  },
];

const products = [
  // ---------------- JF Pin Loaded Series (JF-001 to JF-024) ----------------
  {
    slug: "jf-001-vertical-chest-press",
    name: "VERTICAL CHEST PRESS",
    categoryId: "pin-loaded",
    modelKind: "chest-press",
    tagline: "Pin-loaded vertical chest press machine for isolated upper-body strength training.",
    specialFeature: "Rectangular iron tube frame with 80-100KGS weight stack",
    specs: {
      "Model Code": "JF-001",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1300*1100*1800 (mm)",
    },
    featured: true,
    featureBullets: [
      "Ergonomic handle grips for natural pressing motion",
      "Adjustable seat height for custom bio-mechanics",
      "Heavy-duty selectorized weight stack",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 85000,
  },
  {
    slug: "jf-002-pec-dec-fly",
    name: "PEC DEC FLY / REAR DELT",
    categoryId: "pin-loaded",
    modelKind: "chest-fly",
    tagline: "Dual-function chest fly and rear deltoid isolation machine.",
    specialFeature: "Independent dual arms with 360-degree rotation",
    specs: {
      "Model Code": "JF-002",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1524*1178*2057 (mm)",
    },
    featured: true,
    featureBullets: [
      "Dual exercise functionality for chest and upper back",
      "Comfortable high-density chest/back pad",
      "Smooth cable ratio for constant tension",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 88000,
  },
  {
    slug: "jf-003-rowing-machine",
    name: "ROWING MACHINE",
    categoryId: "pin-loaded",
    modelKind: "rower",
    tagline: "Seated cable row machine for full back thickness and lats.",
    specialFeature: "Elevated footplates and smooth low pulley cable",
    specs: {
      "Model Code": "JF-003",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "2184*812*1930 (mm)",
    },
    featured: false,
    featureBullets: [
      "Non-slip steel footrests",
      "Smooth glide pulley system",
      "Heavy weight stack capacity",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 82000,
  },
  {
    slug: "jf-004-dip-chin-assist",
    name: "DIP / CHIN ASSIST",
    categoryId: "pin-loaded",
    modelKind: "dip-chin",
    tagline: "Counter-balanced weight-assisted pull-up and dip station.",
    specialFeature: "Foldable knee pad for unassisted bodyweight training",
    specs: {
      "Model Code": "JF-004",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1727*1625*1371 (mm)",
    },
    featured: true,
    featureBullets: [
      "Multi-position chin-up handles",
      "Assisted counter-weight stack",
      "Step-up platforms for easy entry",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 95000,
  },
  {
    slug: "jf-005-lat-pull-down",
    name: "LAT PULL DOWN",
    categoryId: "pin-loaded",
    modelKind: "lat-pulldown",
    tagline: "High pulley lat pulldown machine for back width build.",
    specialFeature: "Adjustable thigh hold-down rollers",
    specs: {
      "Model Code": "JF-005",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1542*1016*2286 (mm)",
    },
    featured: false,
    featureBullets: [
      "Heavy-duty aircraft grade cable",
      "Contoured leg restraint cushion",
      "Wide lat bar included",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 80000,
  },
  {
    slug: "jf-006-leg-extension",
    name: "LEG EXTENSION",
    categoryId: "pin-loaded",
    modelKind: "leg-extension",
    tagline: "Targeted quadriceps isolation machine.",
    specialFeature: "Self-adjusting lower shin pad and adjustable back seat",
    specs: {
      "Model Code": "JF-006",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1447*1066*1422 (mm)",
    },
    featured: false,
    featureBullets: [
      "CAM curve matches natural quad torque",
      "Side stability handles",
      "Quick pin adjustments",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 82000,
  },
  {
    slug: "jf-007-overhead-machine",
    name: "OVER HEAD MACHINE",
    categoryId: "pin-loaded",
    modelKind: "shoulder-press",
    tagline: "Seated overhead shoulder press station.",
    specialFeature: "Converging press arms for natural shoulder articulation",
    specs: {
      "Model Code": "JF-007",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1727*1600*1524 (mm)",
    },
    featured: false,
    featureBullets: [
      "Multi-grip neutral and wide handles",
      "Ergonomic angled seat pad",
      "Smooth belt drive / cable system",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 84000,
  },
  {
    slug: "jf-008-prone-leg-curl",
    name: "PRONE LEG CURL",
    categoryId: "pin-loaded",
    modelKind: "leg-curl",
    tagline: "Lying hamstring curl machine for maximum knee flexion strength.",
    specialFeature: "Angled prone hip pad to prevent lower back hyperextension",
    specs: {
      "Model Code": "JF-008",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1727*1041*1422 (mm)",
    },
    featured: false,
    featureBullets: [
      "Contoured leg roller",
      "Handles for stabilization during heavy lifts",
      "Heavy iron stack",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 82000,
  },
  {
    slug: "jf-009-seated-leg-curl-with-ext",
    name: "SEATED LEG CURL WITH EXTENSION",
    categoryId: "pin-loaded",
    modelKind: "leg-curl",
    tagline: "Seated hamstring isolation with thigh hold-down bar.",
    specialFeature: "Combined seated curl and extension ergonomics",
    specs: {
      "Model Code": "JF-009",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1676*956*1422 (mm)",
    },
    featured: false,
    featureBullets: [
      "Adjustable thigh restraint pad",
      "Easy range-of-motion limiter switch",
      "High comfort upholstery",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 86000,
  },
  {
    slug: "jf-010-leg-curl-extension-combo",
    name: "LEG CURL & LEG EXTENSION COMBO",
    categoryId: "pin-loaded",
    modelKind: "leg-combo",
    tagline: "Space-saving dual leg station for quads and hamstrings.",
    specialFeature: "Quick release pin switcher between curl & extension",
    specs: {
      "Model Code": "JF-010",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1524*1701*2057 (mm)",
    },
    featured: true,
    featureBullets: [
      "Dual exercise versatility",
      "Ideal for compact gym footprints",
      "Full leg workout on a single stack",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 92000,
  },
  {
    slug: "jf-011-half-cable-cross-over",
    name: "HALF CABLE CROSS OVER",
    categoryId: "pin-loaded",
    modelKind: "cable-crossover",
    tagline: "Single column adjustable height pulley station.",
    specialFeature: "180-degree swivel pulley bracket",
    specs: {
      "Model Code": "JF-011",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1168*838*2311 (mm)",
    },
    featured: false,
    featureBullets: [
      "Ultra-smooth height adjustment pop-pin",
      "Compact corner footprint",
      "Multi-purpose attachment ring",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 78000,
  },
  {
    slug: "jf-012-lat-pull-down-rowing-single-pulley",
    name: "LAT PULL DOWN / ROWING SINGLE PULLEY",
    categoryId: "pin-loaded",
    modelKind: "pulley-combo",
    tagline: "Dual high/low cable combo for vertical and horizontal pulls.",
    specialFeature: "Single weight stack serving lat pulldown and low row",
    specs: {
      "Model Code": "JF-012",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1524*1016*2489 (mm)",
    },
    featured: false,
    featureBullets: [
      "Integrated foot braces for row position",
      "Thigh pads for lat pulldown",
      "Heavy duty cable guide",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 88000,
  },
  {
    slug: "jf-013-preacher-curl-machine",
    name: "PREACHER CURL MACHINE",
    categoryId: "pin-loaded",
    modelKind: "bicep-curl",
    tagline: "Selectorized bicep isolation machine with preacher pad.",
    specialFeature: "Ergonomic elbow pad for complete bicep isolation",
    specs: {
      "Model Code": "JF-013",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1270*914*1422 (mm)",
    },
    featured: false,
    featureBullets: [
      "Rotating hand grips fit user arm length",
      "Angled arm pad keeps shoulders stable",
      "Smooth cable feel",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 78000,
  },
  {
    slug: "jf-014-standing-lateral-raise",
    name: "STANDING LATERAL RAISE",
    categoryId: "pin-loaded",
    modelKind: "lateral-raise",
    tagline: "Standing shoulder deltoid isolation machine.",
    specialFeature: "Padded arm rollers with foot platform",
    specs: {
      "Model Code": "JF-014",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1295*762*2057 (mm)",
    },
    featured: false,
    featureBullets: [
      "Direct deltoid activation without grip fatigue",
      "Non-slip foot plate",
      "Precision pivot points",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 82000,
  },
  {
    slug: "jf-015-seated-lateral-raise",
    name: "SEATED LATERAL RAISE",
    categoryId: "pin-loaded",
    modelKind: "lateral-raise",
    tagline: "Seated lateral deltoid raise station.",
    specialFeature: "Chest pad support for strict lateral raises",
    specs: {
      "Model Code": "JF-015",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "863*1117*1676 (mm)",
    },
    featured: false,
    featureBullets: [
      "Seated posture prevents momentum cheating",
      "Comfortable arm cushion pads",
      "Independent arm motion option",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 80000,
  },
  {
    slug: "jf-016-cable-cross-over",
    name: "CABLE CROSS OVER",
    categoryId: "pin-loaded",
    modelKind: "cable-crossover",
    tagline: "Full-size dual stack cable crossover machine with chin-up bar.",
    specialFeature: "Dual 80-100KG weight stacks & multi-grip pull up bar",
    specs: {
      "Model Code": "JF-016",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "3581*635*2286 (mm)",
    },
    featured: true,
    featureBullets: [
      "Wide span cable setup for complete chest crossover",
      "Integrated multi-grip pull up station",
      "Adjustable pulley heights along vertical beam",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 145000,
  },
  {
    slug: "jf-017-functional-trainer",
    name: "FUNCTIONAL TRAINER",
    categoryId: "pin-loaded",
    modelKind: "functional-trainer",
    tagline: "Compact dual-stack functional training machine.",
    specialFeature: "Dual weight stacks with high-density pulley adjusters",
    specs: {
      "Model Code": "JF-017",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1930*1524*1701 (mm)",
    },
    featured: true,
    featureBullets: [
      "Multi-angle cable movements for full body",
      "Built-in chin bar",
      "Includes D-handles and accessory hooks",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 135000,
  },
  {
    slug: "jf-018-multy-press-machine",
    name: "MULTY PRESS MACHINE",
    categoryId: "pin-loaded",
    modelKind: "chest-press",
    tagline: "Multi-angle chest and shoulder press combo machine.",
    specialFeature: "Adjustable back rest for flat, incline & shoulder press",
    specs: {
      "Model Code": "JF-018",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1727*1625*1447 (mm)",
    },
    featured: false,
    featureBullets: [
      "3-in-1 pressing angle versatility",
      "Ergonomic handle placement",
      "Quick pop-pin seat adjustment",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 89000,
  },
  {
    slug: "jf-019-wrist-curl",
    name: "WRIST CURL",
    categoryId: "pin-loaded",
    modelKind: "forearm-curl",
    tagline: "Forearm flexor and extensor wrist curl machine.",
    specialFeature: "Padded forearm rest with isolated wrist rotation cam",
    specs: {
      "Model Code": "JF-019",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "660*711*1066 (mm)",
    },
    featured: false,
    featureBullets: [
      "Targeted grip and forearm strength development",
      "Ultra-compact footprint",
      "Smooth cable travel",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 52000,
  },
  {
    slug: "jf-020-smith-with-functional-trainer",
    name: "SMITH WITH FUNCTIONAL TRAINER",
    categoryId: "pin-loaded",
    modelKind: "smith-machine",
    tagline: "All-in-one Smith machine, functional trainer & squat rack.",
    specialFeature: "Linear bearing Smith bar + dual cable weight stacks",
    specs: {
      "Model Code": "JF-020",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1701*2108*2311 (mm)",
    },
    featured: true,
    featureBullets: [
      "Ultra-smooth guided Smith barbell path",
      "Integrated plate storage pegs",
      "Complete commercial power rack functionality",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 185000,
  },
  {
    slug: "jf-021-lat-pull-down-rowing-dual-pulley",
    name: "LAT PULL DOWN / ROWING DUAL PULLEY",
    categoryId: "pin-loaded",
    modelKind: "pulley-combo",
    tagline: "Dual pulley lat pulldown and seated row station.",
    specialFeature: "Independent dual cable pulleys for unilateral pulling",
    specs: {
      "Model Code": "JF-021",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1524*1016*2286 (mm)",
    },
    featured: false,
    featureBullets: [
      "Dual handles allow natural converging arm motion",
      "Heavy duty steel frame",
      "High density foam leg pads",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 92000,
  },
  {
    slug: "jf-022-abdominal-crunch-machine",
    name: "ABDOMINAL BENCH / CRUNCH MACHINE",
    categoryId: "pin-loaded",
    modelKind: "ab-bench",
    tagline: "Selectorized abdominal crunch machine.",
    specialFeature: "Ergonomic swivel chest/shoulder pads and foot catches",
    specs: {
      "Model Code": "JF-022",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "1244*1117*1651 (mm)",
    },
    featured: false,
    featureBullets: [
      "Isolates rectus abdominis without hip flexor pull",
      "Counterbalanced arm mechanism",
      "Adjustable seat height",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 76000,
  },
  {
    slug: "jf-023-adductor-abductor",
    name: "ADDUCTOR / ABDUCTOR",
    categoryId: "pin-loaded",
    modelKind: "hip-adductor",
    tagline: "Dual inner and outer thigh isolation machine.",
    specialFeature: "Swivel thigh pads for seamless switch between exercises",
    specs: {
      "Model Code": "JF-023",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS",
      "Dimension": "810*1830*1500 (mm)",
    },
    featured: false,
    featureBullets: [
      "Dual exercise function saves floor space",
      "Multiple starting position adjustment points",
      "Reclined backrest for pelvic stability",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 84000,
  },
  {
    slug: "jf-024-multi-station",
    name: "MULTI STATION (4, 5, 8 STATIONS)",
    categoryId: "pin-loaded",
    modelKind: "multi-station",
    tagline: "Customizable multi-jungle multi-station gym complex.",
    specialFeature: "Available in 4, 5, and 8 station configurations",
    specs: {
      "Model Code": "JF-024",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Weight Stack": "80-100KGS per stack",
      "Available Size": "4, 5, 8 STATIONS",
    },
    featured: true,
    featureBullets: [
      "Supports 4 to 8 users simultaneously",
      "Includes lat pull, low row, tricep press & cable cross",
      "Ultimate centerpiece for commercial fitness centers",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 295000,
  },

  // ---------------- JF Hammer Series (JF-H-001 to JF-H-025) ----------------
  {
    slug: "jf-h-001-dual-axis-flat-bench",
    name: "DUAL AXIS FLAT BENCH",
    categoryId: "hammer",
    modelKind: "chest-press",
    tagline: "Plate-loaded dual axis horizontal bench press.",
    specialFeature: "Iso-Lateral movement arms with weight horns",
    specs: {
      "Model Code": "JF-001 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: true,
    featureBullets: [
      "Independent arm motion for equal strength development",
      "Heavy-gauge steel frame build",
      "Integrated plate storage pins",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 68000,
  },
  {
    slug: "jf-h-002-dual-axis-incline-bench",
    name: "DUAL AXIS INCLINE BENCH",
    categoryId: "hammer",
    modelKind: "chest-press",
    tagline: "Plate-loaded incline bench press for upper chest hypertrophy.",
    specialFeature: "Converging motion path mimics barbell press",
    specs: {
      "Model Code": "JF-002 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: false,
    featureBullets: [
      "30-degree incline angle for optimal chest activation",
      "Thick high-density padding",
      "Heavy duty load capacity",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 70000,
  },
  {
    slug: "jf-h-003-dual-axis-decline-bench",
    name: "DUAL AXIS DECLINE BENCH",
    categoryId: "hammer",
    modelKind: "chest-press",
    tagline: "Plate-loaded decline bench press machine.",
    specialFeature: "Decline angle path with leg catch rollers",
    specs: {
      "Model Code": "JF-003 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: false,
    featureBullets: [
      "Targeted lower pectoral isolation",
      "Contoured ankle catch rollers for stability",
      "Industrial grade pillow block bearings",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 72000,
  },
  {
    slug: "jf-h-004-iso-lateral-45-leg-press",
    name: "ISO-LATERAL 45° LEG PRESS",
    categoryId: "hammer",
    modelKind: "leg-press",
    tagline: "Dual footplate 45-degree leg press machine.",
    specialFeature: "Independent left & right footplate carriages",
    specs: {
      "Model Code": "JF-004 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED 45 DEGREE",
    },
    featured: true,
    featureBullets: [
      "Iso-lateral leg training prevents leg strength imbalance",
      "Heavy duty linear bearing track",
      "Adjustable seat back angle",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 125000,
  },
  {
    slug: "jf-h-005-45-leg-press",
    name: "45° LEG PRESS",
    categoryId: "hammer",
    modelKind: "leg-press",
    tagline: "Standard commercial 45-degree plate-loaded leg press.",
    specialFeature: "Massive solid footplate with safety lockout handles",
    specs: {
      "Model Code": "JF-005 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED 45 DEGREE",
    },
    featured: true,
    featureBullets: [
      "Rated for up to 500KG loading capacity",
      "Extra wide non-slip diamond tread platform",
      "Dual safety stop positions",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 110000,
  },
  {
    slug: "jf-h-006-super-squat",
    name: "SUPER SQUAT",
    categoryId: "hammer",
    modelKind: "squat",
    tagline: "Plate-loaded leverage super squat machine.",
    specialFeature: "Shoulder pad leverage arm for joint-friendly squats",
    specs: {
      "Model Code": "JF-006 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: false,
    featureBullets: [
      "Natural arc movement reduces lumbar spine stress",
      "Large angled foot platform",
      "Easily accessible safety release handle",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 98000,
  },
  {
    slug: "jf-h-007-smith-squat-rack",
    name: "SMITH + SQUAT RACK",
    categoryId: "hammer",
    modelKind: "smith-machine",
    tagline: "Combined Smith machine and free weight squat rack.",
    specialFeature: "Dual function Smith guide rods and front J-hooks",
    specs: {
      "Model Code": "JF-007 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "HEAVY DUTY COMBINATION",
    },
    featured: false,
    featureBullets: [
      "Counterbalanced Smith barbell option",
      "Adjustable safety spotter arms",
      "Multiple weight storage pegs",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 130000,
  },
  {
    slug: "jf-h-008-smith-power-rack",
    name: "SMITH + POWER RACK",
    categoryId: "hammer",
    modelKind: "power-rack",
    tagline: "Full cage power rack with built-in Smith mechanism.",
    specialFeature: "Enclosed power cage design with integrated Smith bar",
    specs: {
      "Model Code": "JF-008 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "POWER CAGE COMBO",
    },
    featured: true,
    featureBullets: [
      "Maximum safety for heavy solo lifts",
      "Cross-member pull up grips",
      "Heavy iron tube construction",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 145000,
  },
  {
    slug: "jf-h-009-hack-squat",
    name: "HACK SQUAT",
    categoryId: "hammer",
    modelKind: "hack-squat",
    tagline: "45-degree hack squat machine for complete quad focus.",
    specialFeature: "Heavy duty shoulder pads and oversized footplate",
    specs: {
      "Model Code": "JF-009 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED 45 DEGREE",
    },
    featured: true,
    featureBullets: [
      "Deep squat range of motion with full back support",
      "Multi-position lockout catches",
      "Smooth roller bearing carriage",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 115000,
  },
  {
    slug: "jf-h-010-lat-pull-down-hammer",
    name: "LAT PULL DOWN HAMMER",
    categoryId: "hammer",
    modelKind: "lat-pulldown",
    tagline: "Iso-Lateral plate loaded lat pulldown machine.",
    specialFeature: "Diverging movement arms for natural lat contraction",
    specs: {
      "Model Code": "JF-010 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: false,
    featureBullets: [
      "Independent arm operation",
      "Thigh lock rollers",
      "Direct weight plate loading",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 75000,
  },
  {
    slug: "jf-h-011-mid-row",
    name: "MID ROW HAMMER",
    categoryId: "hammer",
    modelKind: "rower",
    tagline: "Seated plate-loaded mid row machine for upper back.",
    specialFeature: "Chest support pad with multi-grip handles",
    specs: {
      "Model Code": "JF-011 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: false,
    featureBullets: [
      "Neutral and horizontal handle orientations",
      "Adjustable seat height",
      "Heavy duty pivot points",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 72000,
  },
  {
    slug: "jf-h-012-low-row",
    name: "LOW ROW HAMMER",
    categoryId: "hammer",
    modelKind: "rower",
    tagline: "Ground-based low row leverage machine.",
    specialFeature: "Low arc movement path targeting lower lats",
    specs: {
      "Model Code": "JF-012 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: false,
    featureBullets: [
      "Iso-lateral arms for unilateral strength work",
      "Rugged frame build",
      "Ergonomic seat cushion",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 74000,
  },
  {
    slug: "jf-h-013-reverse-lat-pull-down",
    name: "REVERSE LAT PULL DOWN",
    categoryId: "hammer",
    modelKind: "lat-pulldown",
    tagline: "Plate-loaded reverse arc lat pulldown station.",
    specialFeature: "Underhand / reverse grip leverage arms",
    specs: {
      "Model Code": "JF-013 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: false,
    featureBullets: [
      "Emphasizes lower lat insertion",
      "Thigh hold rollers",
      "Smooth leverage arm pivot",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 76000,
  },
  {
    slug: "jf-h-014-lat-pull-chest-press-hammer",
    name: "LAT PULL + CHEST PRESS HAMMER",
    categoryId: "hammer",
    modelKind: "combo-press",
    tagline: "Dual-direction pull and press combo leverage machine.",
    specialFeature: "Bi-directional arm mechanism for push and pull work",
    specs: {
      "Model Code": "JF-014 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED COMBO",
    },
    featured: true,
    featureBullets: [
      "Two core upper body exercises in one station",
      "Saves gym floor space",
      "Heavy gauge iron construction",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 88000,
  },
  {
    slug: "jf-h-015-standing-leg-curl",
    name: "STANDING LEG CURL HAMMER",
    categoryId: "hammer",
    modelKind: "leg-curl",
    tagline: "Unilateral standing hamstring curl machine.",
    specialFeature: "Standing posture with hip support pad",
    specs: {
      "Model Code": "JF-015 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED UNILATERAL",
    },
    featured: false,
    featureBullets: [
      "Isolates each leg individually",
      "Comfortable chest/hip rest pad",
      "Direct weight horn loading",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 68000,
  },
  {
    slug: "jf-h-016-shoulder-press-hammer",
    name: "SHOULDER PRESS HAMMER",
    categoryId: "hammer",
    modelKind: "shoulder-press",
    tagline: "Plate-loaded iso-lateral overhead shoulder press machine.",
    specialFeature: "Converging overhead motion path",
    specs: {
      "Model Code": "JF-016 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: false,
    featureBullets: [
      "Natural movement trajectory protects shoulder joints",
      "Neutral & wide grip options",
      "Heavy load capacity",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 74000,
  },
  {
    slug: "jf-h-017-side-raise-with-bend-over",
    name: "SIDE RAISE WITH BEND OVER",
    categoryId: "hammer",
    modelKind: "lateral-raise",
    tagline: "Leverage lateral raise and bent-over rear delt machine.",
    specialFeature: "Standing foot platform with counter-balanced arms",
    specs: {
      "Model Code": "JF-017 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: false,
    featureBullets: [
      "Trains both side delts and rear delts",
      "Non-slip foot plate",
      "Smooth pivot bearings",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 78000,
  },
  {
    slug: "jf-h-018-chest-press-hammer",
    name: "CHEST PRESS HAMMER",
    categoryId: "hammer",
    modelKind: "chest-press",
    tagline: "Iso-Lateral plate-loaded horizontal chest press machine.",
    specialFeature: "Converging arm arc for maximal chest squeeze",
    specs: {
      "Model Code": "JF-018 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: false,
    featureBullets: [
      "Independent left and right leverage arms",
      "Adjustable seat depth",
      "Heavy steel tube chassis",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 72000,
  },
  {
    slug: "jf-h-019-half-rack",
    name: "HALF RACK HAMMER",
    categoryId: "hammer",
    modelKind: "power-rack",
    tagline: "Commercial half power rack with multi-grip chin bar.",
    specialFeature: "Heavy duty uprights with laser-cut numbering",
    specs: {
      "Model Code": "JF-019 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "HALF POWER RACK",
    },
    featured: false,
    featureBullets: [
      "Includes heavy duty J-hooks and safety spotter arms",
      "Integrated plate storage horns",
      "Open front floor space for bench work",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 65000,
  },
  {
    slug: "jf-h-020-ab-crunch-hammer",
    name: "AB CRUNCH HAMMER",
    categoryId: "hammer",
    modelKind: "ab-bench",
    tagline: "Plate-loaded abdominal crunch leverage machine.",
    specialFeature: "Dual upper body and leg leverage crunch pivot",
    specs: {
      "Model Code": "JF-020 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: false,
    featureBullets: [
      "Simultaneous abdominal contraction from top and bottom",
      "Padded ankle catches",
      "Ergonomic headrest",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 64000,
  },
  {
    slug: "jf-h-021-bisolateral-biceps-curl",
    name: "BISOLATERAL BICEPS CURL",
    categoryId: "hammer",
    modelKind: "bicep-curl",
    tagline: "Iso-Lateral plate-loaded bicep curl machine.",
    specialFeature: "Independent arm preacher curl arms",
    specs: {
      "Model Code": "JF-021 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED ISO-LATERAL",
    },
    featured: false,
    featureBullets: [
      "Allows single or double arm bicep curls",
      "Contoured elbow support cushion",
      "Rotating grip handles",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 66000,
  },
  {
    slug: "jf-h-022-hip-thrust",
    name: "HIP THRUST HAMMER",
    categoryId: "hammer",
    modelKind: "hip-thrust",
    tagline: "Dedicated plate-loaded hip thrust glute machine.",
    specialFeature: "Padded waist bar with foot deck platform",
    specs: {
      "Model Code": "JF-022 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED GLUTE MACHINE",
    },
    featured: true,
    featureBullets: [
      "Maximum glute activation with safety restraint bar",
      "Non-slip foot plate angle",
      "Easy loading plate pins",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 78000,
  },
  {
    slug: "jf-h-023-pull-over",
    name: "PULL OVER HAMMER",
    categoryId: "hammer",
    modelKind: "lat-pulldown",
    tagline: "Plate-loaded full rotational lat pullover machine.",
    specialFeature: "Full 360-degree shoulder extension arm motion",
    specs: {
      "Model Code": "JF-023 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED PULLOVER",
    },
    featured: false,
    featureBullets: [
      "Isolates lats through full arc without arm fatigue",
      "Seatbelt safety strap",
      "Counter-weighted leverage arm",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 84000,
  },
  {
    slug: "jf-h-024-vertical-chest-press-hammer",
    name: "VERTICAL CHEST PRESS HAMMER",
    categoryId: "hammer",
    modelKind: "chest-press",
    tagline: "Plate-loaded vertical posture chest press station.",
    specialFeature: "Upright seat position with foot-assisted start pedal",
    specs: {
      "Model Code": "JF-024 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED",
    },
    featured: false,
    featureBullets: [
      "Foot lever helps bring handles into start position safely",
      "Heavy steel tube construction",
      "High density foam upholstery",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 74000,
  },
  {
    slug: "jf-h-025-verticle-90-leg-press",
    name: "VERTICLE 90° LEG PRESS",
    categoryId: "hammer",
    modelKind: "leg-press",
    tagline: "True 90-degree vertical plate-loaded leg press machine.",
    specialFeature: "Vertical slide carriage with safety lockout pins",
    specs: {
      "Model Code": "JF-025 (Hammer)",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Type": "PLATE LOADED 90 DEGREE VERTICAL",
    },
    featured: true,
    featureBullets: [
      "Ultimate hamstring and glute loaded 90 degree angle",
      "Reclined backrest pad",
      "Triple safety catches",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 95000,
  },

  // ---------------- JF Benches & Utilities (JF-GE-001 to JF-GE-016) ----------------
  {
    slug: "jf-ge-001-adjustable-bench",
    name: "ADJUSTABLE BENCH",
    categoryId: "benches-utilities",
    modelKind: "bench",
    tagline: "Multi-angle incline/decline/flat utility workout bench.",
    specialFeature: "Heavy-duty ladder tooth angle adjustment mechanism",
    specs: {
      "Model Code": "JF-GE-001",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "1600*762*457(mm)",
    },
    featured: true,
    featureBullets: [
      "Adjusts from decline to flat to 85-degree incline",
      "Transport wheels and grab handle",
      "High density tear-resistant vinyl",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 28000,
  },
  {
    slug: "jf-ge-002-simple-bench",
    name: "SIMPLE BENCH",
    categoryId: "benches-utilities",
    modelKind: "bench",
    tagline: "Heavy-duty commercial flat utility bench.",
    specialFeature: "Solid welded steel frame structure with rubber feet",
    specs: {
      "Model Code": "JF-GE-002",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "1100*406*406(mm)",
    },
    featured: false,
    featureBullets: [
      "Rated for 400KG total load",
      "Stable 3-point or 4-point stance",
      "Ideal for dumbbell and barbell workouts",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 15000,
  },
  {
    slug: "jf-ge-003-oly-decline-bench",
    name: "OLY DECLINE BENCH",
    categoryId: "benches-utilities",
    modelKind: "olympic-bench",
    tagline: "Olympic decline bench press with integrated bar catches.",
    specialFeature: "Gun-rack barbell catches with leg hold rollers",
    specs: {
      "Model Code": "JF-GE-003",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "2184*1727*1143(mm)",
    },
    featured: false,
    featureBullets: [
      "Fixed decline angle for lower chest",
      "Ankle foam rollers for secure position",
      "Built-in plate storage pegs",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 45000,
  },
  {
    slug: "jf-ge-004-oly-incline-bench",
    name: "OLY INCLINE BENCH",
    categoryId: "benches-utilities",
    modelKind: "olympic-bench",
    tagline: "Olympic incline bench press station with spotter stand.",
    specialFeature: "Integrated rear spotter platform and multi-tier bar hooks",
    specs: {
      "Model Code": "JF-GE-004",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "1955*1727*1498(mm)",
    },
    featured: false,
    featureBullets: [
      "Heavy duty spotter platform",
      "30-degree incline pad angle",
      "Weight plate storage horns",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 48000,
  },
  {
    slug: "jf-ge-005-oly-flat-bench",
    name: "OLY FLAT BENCH",
    categoryId: "benches-utilities",
    modelKind: "olympic-bench",
    tagline: "Standard Olympic flat bench press rack.",
    specialFeature: "Durable molded urethane bar catch guards",
    specs: {
      "Model Code": "JF-GE-005",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "1727*1727*1193(mm)",
    },
    featured: true,
    featureBullets: [
      "Commercial gym standard flat bench press",
      "Multiple bar catch height levels",
      "Side plate storage posts",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 42000,
  },
  {
    slug: "jf-ge-006-oly-multi-purpose-bench",
    name: "OLY MULTI PURPOSE BENCH",
    categoryId: "benches-utilities",
    modelKind: "olympic-bench",
    tagline: "Multi-angle Olympic barbell pressing bench.",
    specialFeature: "Adjustable bench pad mounted within Olympic rack uprights",
    specs: {
      "Model Code": "JF-GE-006",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "660*1772*1447(mm)",
    },
    featured: false,
    featureBullets: [
      "Allows flat, incline, and shoulder pressing",
      "Heavy duty steel frame",
      "Footrest attachment",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 54000,
  },
  {
    slug: "jf-ge-007-ab-bench",
    name: "AB BENCH",
    categoryId: "benches-utilities",
    modelKind: "ab-bench",
    tagline: "Adjustable decline abdominal sit-up bench.",
    specialFeature: "Multi-level decline pin adjustment with leg rollers",
    specs: {
      "Model Code": "JF-GE-007",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "1700*685*838(mm)",
    },
    featured: false,
    featureBullets: [
      "Vary sit-up resistance via decline angle",
      "Thick leg support rollers",
      "Transport wheels",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 24000,
  },
  {
    slug: "jf-ge-008-preacher-curl-bench",
    name: "PREACHER CURL BENCH",
    categoryId: "benches-utilities",
    modelKind: "preacher-bench",
    tagline: "Seated preacher bicep curl bench with barbell hooks.",
    specialFeature: "Angled preacher arm pad with front bar cradle hooks",
    specs: {
      "Model Code": "JF-GE-008",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "1346*838*1727(mm)",
    },
    featured: false,
    featureBullets: [
      "Isolates biceps for EZ-bar or dumbbell curls",
      "Adjustable seat height",
      "Heavy steel bar hooks",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 26000,
  },
  {
    slug: "jf-ge-009-standing-preacher",
    name: "STANDING PREACHER",
    categoryId: "benches-utilities",
    modelKind: "preacher-bench",
    tagline: "Standing preacher arm curl support rack.",
    specialFeature: "Standing posture arm pad height adjustable",
    specs: {
      "Model Code": "JF-GE-009",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "1066*787*1117(mm)",
    },
    featured: false,
    featureBullets: [
      "Allows strict standing bicep curls",
      "Dual height barbell rack hooks",
      "Compact footprint",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 22000,
  },
  {
    slug: "jf-ge-010-utility-stool",
    name: "UTILITY STOOL",
    categoryId: "benches-utilities",
    modelKind: "utility-stool",
    tagline: "Seated 90-degree upright utility seat for dumbbell presses.",
    specialFeature: "Fixed 90-degree vertical back pad with foot pegs",
    specs: {
      "Model Code": "JF-GE-010",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "1050*550*900(mm)",
    },
    featured: false,
    featureBullets: [
      "Provides lumbar support for overhead dumbbell work",
      "Low profile frame easy to move",
      "Heavy-duty vinyl seat cover",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 14000,
  },
  {
    slug: "jf-ge-011-adjustable-bench-iso",
    name: "ADJUSTABLE BENCH ISO",
    categoryId: "benches-utilities",
    modelKind: "bench",
    tagline: "Precision ISO adjustable incline bench.",
    specialFeature: "Arc track angle selector for ultra-fine adjustments",
    specs: {
      "Model Code": "JF-GE-011",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "1447*736*457(mm)",
    },
    featured: false,
    featureBullets: [
      "Arc rail adjustment mechanism for instant angle change",
      "Zero gap pad alignment",
      "Heavy duty rubber floor pads",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 32000,
  },
  {
    slug: "jf-ge-012-bar-dip",
    name: "BAR DIP",
    categoryId: "benches-utilities",
    modelKind: "dip-station",
    tagline: "Bodyweight dip and vertical knee raise station.",
    specialFeature: "Angled dip handles with forearm armrests and back pad",
    specs: {
      "Model Code": "JF-GE-012",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "1370*838*1676(mm)",
    },
    featured: false,
    featureBullets: [
      "Trains chest, triceps, and abdominal core",
      "Step-up foot pegs",
      "Comfortable armrest cushions",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 25000,
  },
  {
    slug: "jf-ge-013-hyper-extension",
    name: "HYPER EXTENSION",
    categoryId: "benches-utilities",
    modelKind: "hyper-extension",
    tagline: "45-degree back hyper extension / roman chair.",
    specialFeature: "Split thigh pads with diamond tread footplate",
    specs: {
      "Model Code": "JF-GE-013",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "1346*787*838(mm)",
    },
    featured: false,
    featureBullets: [
      "Strengthens lower back, glutes, and hamstrings",
      "Telescoping pad adjustment for user height",
      "Assistance handles for easy mount/dismount",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 22000,
  },
  {
    slug: "jf-ge-014-roman-bench",
    name: "ROMAN BENCH",
    categoryId: "benches-utilities",
    modelKind: "hyper-extension",
    tagline: "Horizontal GHD / Roman chair abdominal & glute bench.",
    specialFeature: "Dual foam ankle rollers with curved hip pad",
    specs: {
      "Model Code": "JF-GE-014",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Dimension": "1300*700(mm)",
    },
    featured: false,
    featureBullets: [
      "GHD sit-ups and back extensions",
      "Quick pin foot pad slider",
      "Heavy commercial base frame",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 28000,
  },
  {
    slug: "jf-ge-015-dumbbell-rack",
    name: "DUMBBELL RACK",
    categoryId: "benches-utilities",
    modelKind: "rack",
    tagline: "Heavy-duty 2-tier or 3-tier dumbbell storage rack.",
    specialFeature: "Available in 2 Layer or 3 Layer configurations with saddles",
    specs: {
      "Model Code": "JF-GE-015",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "Available Size": "2 LAYER OR 3 LAYER",
    },
    featured: true,
    featureBullets: [
      "Individual dumbbell cradle saddles prevent rolling",
      "Angled shelves for easy loading and un-rack",
      "Holds 10 to 15 pairs of dumbbells",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 35000,
  },
  {
    slug: "jf-ge-016-plate-rack",
    name: "PLATE RACK",
    categoryId: "benches-utilities",
    modelKind: "rack",
    tagline: "A-frame Olympic weight plate tree storage rack.",
    specialFeature: "09 Holders for Olympic plates and bar storage",
    specs: {
      "Model Code": "JF-GE-016",
      "Main Frame": "RECTANGULAR IRON TUBE",
      "No. of Holders": "09 HOLDERS",
    },
    featured: false,
    featureBullets: [
      "9 chrome plate pegs accommodate all bumper and steel plate sizes",
      "Integrated vertical barbell holder slots",
      "Rubber bumper foot caps",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 18000,
  },

  // ---------------- JF GYM Accessories ----------------
  {
    slug: "jf-acc-dumbbell",
    name: "COMMERCIAL DUMBBELLS",
    categoryId: "gym-accessories",
    modelKind: "dumbbell",
    tagline: "Precision CPU/Rubber encased solid steel commercial dumbbells.",
    specialFeature: "Available in pairs from 2.5 KG to 50 KG",
    specs: {
      "Product Type": "Rubber Encased Dumbbell",
      "Available Sizes": "2.5 TO 50KGS",
      "Grip": "Contoured Chrome Knurled Handle",
    },
    featured: true,
    featureBullets: [
      "Heavy-duty rubber casing protects gym flooring",
      "Clear embossed weight indicators in KG",
      "Maintenance-free solid steel press-fit heads",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 220,
  },
  {
    slug: "jf-acc-plates",
    name: "COMMERCIAL WEIGHT PLATES",
    categoryId: "gym-accessories",
    modelKind: "weight-plate",
    tagline: "Tri-grip rubber coated Olympic weight plates.",
    specialFeature: "3-handle tri-grip design for safe manual handling",
    specs: {
      "Product Type": "Tri-Grip Rubber Plate",
      "Available Sizes": "2.5 TO 25KGS",
      "Collar Diameter": "50mm Olympic Standard",
    },
    featured: false,
    featureBullets: [
      "Tri-grip handles enable standalone plate exercises",
      "Stainless steel center bushing",
      "Odourless natural rubber casing",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 200,
  },
  {
    slug: "jf-acc-bumper-plates",
    name: "COMPETITION BUMPER PLATES",
    categoryId: "gym-accessories",
    modelKind: "bumper-plate",
    tagline: "Color-coded solid virgin rubber Olympic bumper plates.",
    specialFeature: "IWF standard color coding & 450mm diameter",
    specs: {
      "Product Type": "Solid Virgin Rubber Bumper Plate",
      "Available Sizes": "5KG TO 25KGS",
      "Diameter": "450mm Standard Bumper Outer Diameter",
    },
    featured: true,
    featureBullets: [
      "Low bounce virgin rubber compound",
      "Color coded (Green 10kg, Yellow 15kg, Blue 20kg, Red 25kg)",
      "Precision brass/steel center hub insert",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 280,
  },
  {
    slug: "jf-acc-rubber-roll-mat",
    name: "RUBBER ROLL MAT",
    categoryId: "gym-accessories",
    modelKind: "flooring",
    tagline: "Seamless high-density EPDM rubber flooring rolls.",
    specialFeature: "Customizable thickness from 2mm up to 10mm",
    specs: {
      "Material": "SBR Rubber with multi-color EPDM flecks",
      "Thickness": "2mm, 4mm, 6mm, 8mm & 10mm",
      "Dimensions": "Length 10m to 20m, Width 1m to 1.2m",
      "Colors": "Green, White, Red, Yellow, Blue, Multi Color",
    },
    featured: false,
    featureBullets: [
      "Absorbs heavy impact noise and vibration",
      "Anti-slip textured surface wet or dry",
      "Easy roll-out installation for large areas",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 65,
  },
  {
    slug: "jf-acc-rubber-square-mat",
    name: "RUBBER SQUARE MAT TILES",
    categoryId: "gym-accessories",
    modelKind: "flooring",
    tagline: "Interlocking and precision paper-cut rubber floor tiles.",
    specialFeature: "Available in V-Groove, Paper-cut, and Interlocking tile formats",
    specs: {
      "Tile Formats": "Laminated V-Groove, Paper-cut, Interlocking Tiles",
      "Colors Available": "Green, White, Red, Yellow, Blue, Multi Color",
      "Application": "Free weight areas and heavy lifting platforms",
    },
    featured: false,
    featureBullets: [
      "Interlocking teeth create seamless floor joint",
      "Heavy shock-absorption for deadlift platforms",
      "Durable non-marking EPDM rubber top",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 180,
  },

  // ---------------- JF Manufacturing & Powder Coating ----------------
  {
    slug: "jf-tool-horizontal-band-saw",
    name: "HORIZONTAL BAND SAW MACHINE",
    categoryId: "professional-tools",
    modelKind: "machinery",
    tagline: "Industrial heavy-duty metal pipe cutting band saw machine.",
    specialFeature: "Precision hydraulic downfeed cutting control",
    specs: {
      "Category": "Professional Tools / Manufacturing",
      "Application": "Heavy Iron Tube Precision Cutting",
    },
    featured: false,
    featureBullets: [
      "Automatic shut-off after cut completion",
      "Coolant pump system for smooth metal cuts",
      "Adjustable miter angle vice",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 250000,
  },
  {
    slug: "jf-tool-pipe-bending-machine",
    name: "PIPE BENDING MACHINE",
    categoryId: "professional-tools",
    modelKind: "machinery",
    tagline: "CNC hydraulic pipe and tube bending machine for gym frames.",
    specialFeature: "Mandrel bending system for wrinkle-free tube curves",
    specs: {
      "Category": "Professional Tools / Manufacturing",
      "Application": "Ergonomic Rectangular & Round Tube Frame Bending",
    },
    featured: false,
    featureBullets: [
      "Programmable multi-bend memory angles",
      "Hydraulic clamping for heavy steel pipe walls",
      "Ensures exact bio-mechanical frame curves",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 650000,
  },
  {
    slug: "jf-tool-metal-cutting-bandsaw",
    name: "METAL CUTTING BANDSAW MACHINE",
    categoryId: "professional-tools",
    modelKind: "machinery",
    tagline: "High-speed metal cutting bandsaw station.",
    specialFeature: "Multi-blade speed belt drive for various alloy gauges",
    specs: {
      "Category": "Professional Tools / Manufacturing",
      "Application": "High-volume frame raw material processing",
    },
    featured: false,
    featureBullets: [
      "High rigidity cast-iron saw frame",
      "Quick clamp vise mechanism",
      "Chip removal brush assembly",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 280000,
  },
  {
    slug: "jf-tool-powder-coating-machine",
    name: "POWDER COATING MACHINE & BOOTH",
    categoryId: "professional-tools",
    modelKind: "machinery",
    tagline: "Electrostatic electrostatic powder coating system & curing booth.",
    specialFeature: "Conveyor overhead track with cyclone powder recovery booth",
    specs: {
      "Category": "Professional Coating Facility",
      "Application": "Industrial Scratch-Resistant Electrostatic Frame Powder Coating",
    },
    featured: true,
    featureBullets: [
      "Provides signature Jakhu Red & Dark Charcoal scratch-resistant finish",
      "Multi-stage pre-treatment wash line",
      "High-temperature baking oven for maximum paint adhesion durability",
    ],
    colorwayBody: "#111827",
    colorwayAccent: "#dc2626",
    price: 850000,
  },
];

async function main() {
  console.log("Starting database seed...");

  // 1. Seed Categories
  for (const cat of categories) {
    await prisma.category.upsert({
      where: { id: cat.id },
      update: {
        name: cat.name,
        blurb: cat.blurb,
      },
      create: {
        id: cat.id,
        name: cat.name,
        blurb: cat.blurb,
      },
    });
  }
  console.log(`Seeded ${categories.length} categories.`);

  // 2. Seed Products & Stock Entries
  let seededCount = 0;
  for (const prod of products) {
    const createdProduct = await prisma.product.upsert({
      where: { slug: prod.slug },
      update: {
        name: prod.name,
        categoryId: prod.categoryId,
        modelKind: prod.modelKind,
        tagline: prod.tagline,
        specialFeature: prod.specialFeature,
        specs: prod.specs,
        featured: prod.featured,
        featureBullets: prod.featureBullets,
        price: prod.price,
        colorwayBody: prod.colorwayBody,
        colorwayAccent: prod.colorwayAccent,
      },
      create: {
        slug: prod.slug,
        name: prod.name,
        categoryId: prod.categoryId,
        modelKind: prod.modelKind,
        tagline: prod.tagline,
        specialFeature: prod.specialFeature,
        specs: prod.specs,
        featured: prod.featured,
        featureBullets: prod.featureBullets,
        price: prod.price,
        colorwayBody: prod.colorwayBody,
        colorwayAccent: prod.colorwayAccent,
      },
    });

    // Ensure Stock Entry exists for inventory tracking
    await prisma.stockEntry.upsert({
      where: { productId: createdProduct.id },
      update: {},
      create: {
        productId: createdProduct.id,
        qty: 10,
        minQty: 2,
      },
    });

    seededCount++;
  }
  console.log(`Seeded ${seededCount} products with stock entries.`);

  console.log("Database seed completed successfully!");
}

main()
  .catch((e) => {
    console.error("Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
